channels:
- defaults
dependencies:
- pip
- pip:
  - addict==2.4.0
  - aiohttp==3.8.6
  - aiosignal==1.3.1
  - albumentations==1.3.1
  - antlr4-python3-runtime==4.9.3
  - anyio==3.7.1
  - appdirs==1.4.4
  - argon2-cffi==23.1.0
  - argon2-cffi-bindings==21.2.0
  - async-timeout==4.0.3
  - asynctest==0.13.0
  - attrs==23.1.0
  - audioread==3.0.0
  - av==10.0.0
  - backcall==0.2.0
  - beautifulsoup4==4.12.2
  - black==23.3.0
  - bleach==6.0.0
  - bs4==0.0.1
  - cachetools==5.3.1
  - certifi @ file:///croot/certifi_1671487769961/work/certifi
  - cffi==1.15.1
  - charset-normalizer==3.1.0
  - click==8.1.3
  - clip @ git+https://github.com/openai/CLIP.git@a1d071733d7111c9c014f024669f959182114e33
  - colorama==0.4.6
  - coloredlogs==15.0.1
  - comm==0.1.4
  - cycler==0.11.0
  - Cython==0.29.36
  - datasets==2.13.2
  - debugpy==1.6.7
  - decorator==4.4.2
  - decord==0.6.0
  - defusedxml==0.7.1
  - dill==0.3.6
  - docker-pycreds==0.4.0
  - easydict==1.10
  - einops==0.6.1
  - entrypoints==0.4
  - exceptiongroup==1.1.3
  - facenet-pytorch==2.5.3
  - fake-useragent==1.2.1
  - fastjsonschema==2.18.0
  - ffmpeg==1.4
  - filelock==3.12.2
  - flatbuffers==23.5.26
  - fonttools==4.38.0
  - frozenlist==1.3.3
  - fsspec==2023.1.0
  - ftfy==6.1.1
  - fvcore==0.1.5.post20221221
  - gitdb==4.0.10
  - GitPython==3.1.31
  - glob2==0.7
  - h5pickle==0.4.2
  - h5py==2.9.0
  - huggingface-hub==0.15.1
  - humanfriendly==10.0
  - idna==3.4
  - imageio==2.31.1
  - imageio-ffmpeg==0.4.8
  - importlib-metadata==4.13.0
  - importlib-resources==5.12.0
  - insightface==0.7.3
  - iopath==0.1.10
  - ipdb==0.13.13
  - ipykernel==6.16.2
  - ipython==7.34.0
  - ipython-genutils==0.2.0
  - ipywidgets==8.1.1
  - jedi==0.18.2
  - Jinja2==3.1.2
  - joblib==1.2.0
  - jsonschema==4.17.3
  - jupyter==1.0.0
  - jupyter-console==6.6.3
  - jupyter-server==1.24.0
  - jupyter_client==7.4.9
  - jupyter_core==4.12.0
  - jupyterlab-pygments==0.2.2
  - jupyterlab-widgets==3.0.9
  - kiwisolver==1.4.4
  - librosa==0.7.2
  - llvmlite==0.31.0
  - lxml==4.9.3
  - MarkupSafe==2.1.3
  - matplotlib==3.5.3
  - matplotlib-inline==0.1.6
  - mistune==3.0.1
  - mmcv==1.0.3
  - moviepy==1.0.3
  - mpmath==1.3.0
  - multidict==6.0.4
  - multiprocess==0.70.14
  - mypy-extensions==1.0.0
  - nbclassic==1.0.0
  - nbclient==0.7.4
  - nbconvert==7.6.0
  - nbformat==5.8.0
  - nest-asyncio==1.5.8
  - networkx==2.6.3
  - nltk==3.8.1
  - notebook==6.5.6
  - notebook_shim==0.2.3
  - numba==0.48.0
  - numpy==1.21.6
  - nvidia-cublas-cu11==11.10.3.66
  - nvidia-cuda-nvrtc-cu11==11.7.99
  - nvidia-cuda-runtime-cu11==11.7.99
  - nvidia-cudnn-cu11==8.5.0.96
  - omegaconf==2.3.0
  - onnx==1.14.0
  - onnxruntime==1.14.1
  - opencv-python==4.8.0.74
  - opencv-python-headless==4.8.0.74
  - packaging==23.1
  - pandas==1.3.5
  - pandocfilters==1.5.0
  - parameterized==0.9.0
  - parso==0.8.3
  - pathspec==0.11.1
  - pathtools==0.1.2
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - Pillow==9.5.0
  - pkgutil_resolve_name==1.3.10
  - platformdirs==3.8.0
  - portalocker==2.7.0
  - prettytable==3.7.0
  - proglog==0.1.10
  - prometheus-client==0.17.1
  - prompt-toolkit==3.0.38
  - protobuf==4.23.3
  - psutil==5.9.5
  - ptyprocess==0.7.0
  - pyarrow==12.0.1
  - pycocoevalcap==1.2
  - pycocotools==2.0.7
  - pycparser==2.21
  - Pygments==2.15.1
  - PyHamcrest==2.0.4
  - pyparsing==3.1.0
  - pyrsistent==0.19.3
  - python-dateutil==2.8.2
  - pytorchvideo==0.1.5
  - pytz==2023.3
  - PyWavelets==1.3.0
  - PyYAML==6.0
  - pyzmq==24.0.1
  - qtconsole==5.4.4
  - QtPy==2.4.0
  - qudida==0.0.4
  - regex==2023.6.3
  - requests==2.31.0
  - resampy==0.3.1
  - sacrebleu==2.3.2
  - safetensors==0.4.2
  - scikit-image==0.19.3
  - scikit-learn==1.0.2
  - scipy==1.7.3
  - seaborn==0.12.2
  - Send2Trash==1.8.2
  - sentencepiece==0.1.99
  - sentry-sdk==1.25.1
  - setproctitle==1.3.2
  - six==1.16.0
  - smmap==5.0.0
  - sniffio==1.3.0
  - soundfile==0.12.1
  - soupsieve==2.4.1
  - sympy==1.10.1
  - tabulate==0.9.0
  - termcolor==2.3.0
  - terminado==0.17.1
  - threadpoolctl==3.1.0
  - tifffile==2021.11.2
  - tinycss2==1.2.1
  - tokenizers==0.13.3
  - tomli==2.0.1
  - torch==1.13.1
  - torchvision==0.14.1
  - tornado==6.2
  - tqdm==4.65.0
  - traitlets==5.9.0
  - transformers==4.30.2
  - typed-ast==1.5.4
  - typing_extensions==4.6.3
  - urllib3==2.0.3
  - wandb==0.15.5
  - wcwidth==0.2.6
  - webencodings==0.5.1
  - websocket-client==1.6.1
  - widgetsnbextension==4.0.9
  - xxhash==3.4.1
  - yacs==0.1.8
  - yapf==0.33.0
  - yarl==1.9.2
  - zipp==3.15.0
name: mst
